import controls
import algorithm

cube = algorithm.RubiksCube('cube_colors.txt')
print("Initial cube state:")
cube.visualize()
print("After U:")
controls.U(cube)
cube.visualize()
print("After U':")
controls.U_prime(cube)
cube.visualize()
print("After B:")
controls.B(cube)
cube.visualize()
print("After B':")
controls.B_prime(cube)
cube.visualize()
print("After F:")
controls.F(cube)
cube.visualize()
print("After F':")
controls.F_prime(cube)
cube.visualize()
print("After L:")
controls.L(cube)
cube.visualize()
print("After L':")
controls.L_prime(cube)
cube.visualize()
print("After R:")
controls.R(cube)
cube.visualize()
print("After R':")
controls.R_prime(cube)
cube.visualize()
print("After D:")
controls.D(cube)
cube.visualize()
print("After D':")
controls.D_prime(cube)
cube.visualize()
